baseURL = "https://lmesg.github.io/"
languageCode = "ko-kr"
title = "lmesg  Security Log"
theme = "PaperMod"

[params]
    env = "production"
    title = "lmesg Security Log"
    description = "2년 차 보안 엔지니어의 학습 기록 및 보안 로그"
    defaultTheme = "auto" # 시스템 설정에 따라 다크모드 자동 적용